---
title: "Introduction to Portfolio Attribution"
author: "[Anand Krishnakumar](https://github.com/anandkkumar)"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
bibliography: introduction.bib
vignette: >
  %\VignetteIndexEntry{Introduction to Portfolio Attribution}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

### <ins>Preliminaries</ins>

The `PortfolioAttribution` package is a implementation of performance return attribution and is largely based on the methodologies documented in the book _Practical Portfolio Performance Measurement and Attribution by Bacon [-@bacon2008practical]_.

Performance attribution allows us to decompose the value added by the portfolio into different components and, thus, to evaluate the quality of investment decisions. This is achieved by the decomposition of the excess returns, relative to a benchmark.

The foundations of performance attribution were established in two articles published by _Brinson et al. [-@brinson1986determinants]_ and _Brinson and Fachler [-@brinson1985measuring]_ now collectively know as the Brinson model. The excess return of a portfolio over a benchmark can be defined as arithmetic excess return or geometric excess return.

### <ins>Arithmetic attribution</ins>
Arithmetic excess return is the profit in excess of a notional or benchmark fund expressed as a percentage of the initial amount invested.

\[
E^A = R_p - R_b
\]


Arithmetic attribution looks to decompose the arithmetic excess return into three attribution effects, _allocation_, _interaction_ and _selection_ effects based on the Brinson model. The allocation effect captures the value added by category bets taken by the portfolio manager, while the selection effect captures the value added by selecting individual securities within the asset category. The remaining interaction effect is a plug term that is required in order for the total of the effects to sum up to the total arithmetic excess return.

Let's assume we divide the portfolio & benchmark into $n$ categories (e.g. by Sector). There are two ways to compute the arithmetic attribution effects as outlined below.

#### Brinson, Hood and Beebower

This method is based on the _Brinson et al. [-@brinson1986determinants]_ article and defines allocation, interaction and selection effects for each category $i$ as

\[
  \begin{aligned}
    A_i = (w_{pi}-w_{bi})\times R_{bi} \\
    S_i = w_{bi}\times(R_{pi}-R_{bi}) \\
    I_i = (w_{pi}-w_{bi})\times(R_{pi}-R_{bi})
  \end{aligned}
\]

The relationship between these attribution effects and the total arithmetic excess return for the portfolio over the benchmark is given by

\[
E^A = R_p - R_b = \sum ^n_{i=1} A_i + \sum ^n_{i=1} S_i + \sum ^n_{i=1} I_i
\]


#### Brinson and Fachler

This method is based on the _Brinson and Fachler [-@brinson1985measuring]_ article and defines interaction and selection effects the same as in the Brinson, Hood and Beebower approach but the allocation effect is defined as

\[
  A_i = (w_{pi} - w_{bi})\times (R_{bi} - R_b)
\]

As before, the relationship between these attribution effects and the total arithmetic excess return for the portfolio over the benchmark is given by
Geometric Excess Return is the profit in excess of a notional or benchmark fund expressed as a percentage of the final value of the notional or benchmark fund.

\[
E^A = R_p - R_b = \sum ^n_{i=1} A_i + \sum ^n_{i=1} S_i + \sum ^n_{i=1} I_i
\]


### <ins>Geometric attribution</ins>

\[
E^G = \frac{(1 + R_p)}{(1 + R_b)} - 1
\]


Geometric attribution extends the Brinson Fachler model to decompose the geometric excess return into two attribution effects, allocation, and selection effects. The semantic meaning of the allocation & selection effects are the same as described earlier with arithmetic attribution. There is no interaction effect in this approach.

Let's assume we divide the portfolio & benchmark into $n$ categories (e.g. by Sector). The allocation, and selection effects for each category $i$ are defined as

\[
  \begin{aligned}
    A_i^G = (w_{pi} - w_{bi}) \times \frac{(1 + R_{bi})}{(1 + R_b)} - 1 \\
    S_i^G = w_{pi} \times \left(\frac{(1 + R_{pi})}{(1 + R_{bi})} - 1\right) \times \frac{(1 + R_{bi})}{(1 + R_{bs})}
  \end{aligned}
\]

where $R_{bs}$, referred to as the allocation notional return, is given by

\[
R_{bs} = \sum^n_{i=1}\left(w_{pi} \times R_{bi} \right)
\]


The relationship between the attribution effects and the total geometric excess return for the entire portfolio over the benchmark is given by
\[
E^G = \frac{(1 + R_p)}{(1+ R_b)} - 1 = \left((1 + \sum ^{n}_{i=1} A_i^G) \times (1 + \sum ^{n}_{i=1} S_i^G)\right) - 1
\]

### <ins>Multi-currency portfolios</ins>

The `PortfolioAttribution` package reports currency effects for arithmetic and geometric attribution analysis. 

#### Multi-currency arithmetic attribution

With arithmetic attriution, the methodology employed follows that described by _Ankrim and Hensel [-@ankrim1994multicurrency]_. According to that approach, the currency return is comprised of two components: the unpredictable _currency surprise_ and the predictable interest rate differential or _forward premium_ between the appropriate currencies.

The currency surprise and forward premium in currency $i$ are given by

\[
  \begin{aligned}
    R_{cei} = \frac{S_i^{t+1} - F_i^{t+1}}{S_i^t} \\
    R_{fpi} = \frac{F_i^{t+1}}{S_i^t} - 1
  \end{aligned}
\]

where $S_i^t$ and $S_t^{t+1}$ are the spot rates of the currency $i$ at times $t$ and $t+1$ and $F_i^{t+1}$ is the forward exchange rate of the currency $i$ at time $t$ for conversion through a forward contract at time $t+1$.

Then currency return is the sum of the currency surprise and the forward premium

\[
R_{ci} = R_{cei} + R_{fpi}
\]

Assuming the currency surprise and forward premiums are the same in the portfolio & benchmark, the total returns to the portfolio and benchmark can be expanded to include these currency returns

\[
  \begin{aligned}
    R_p = \sum^n_{i=1}\left(w_{pi} \times(R_{pi} - R_{cei} - R_{fpi})\right) + \sum^n_{i=1}\left(w_{pi} \times R_{cei}\right) + \sum^n_{i=1}\left(w_{pi} \times R_{fpi}\right) \\
    R_b = \sum^n_{i=1}\left(w_{bi} \times(R_{bi} - R_{cei} - R_{fpi})\right) + \sum^n_{i=1}\left(w_{bi} \times R_{cei}\right) + \sum^n_{i=1}\left(w_{bi} \times R_{fpi}\right)
  \end{aligned}
\]

If the portfolio and benchmark also includes forward currency contracts, these can then be further isolated from the rest of the sources of return. If the weights of the forward contracts in the portfolio and benchmark are $w_{pfi}$ and $w_{bfi}$ respectively, then the forward return due to the curreny contracts can be expressed as

\[
  R_{fi} = \frac{S_i^{t+1}}{F_i^{t+1}} - 1
\]

Assuming the currency forward contract returns are the same in the portfolio & benchmark, the total returns to the portfolio and benchmark with the forward contracts included are now expressed as

\[
  \begin{aligned}
    R_p = \sum^n_{i=1}\left(w_{pi} \times(R_{pi} - R_{cei} - R_{fpi})\right) + \sum^n_{i=1}\left(w_{pi} \times R_{cei}\right) + \sum^n_{i=1}\left(w_{pi} \times R_{fpi}\right) + \sum^n_{i=1}\left(w_{pfi} \times R_{fi}\right) \\
    R_b = \sum^n_{i=1}\left(w_{bi} \times(R_{bi} - R_{cei} - R_{fpi})\right) + \sum^n_{i=1}\left(w_{bi} \times R_{cei}\right) + \sum^n_{i=1}\left(w_{bi} \times R_{fpi}\right) + \sum^n_{i=1}\left(w_{bfi} \times R_{fi}\right)
  \end{aligned}
\]

The allocation, selection and interaction effects for category $i$ are as shown below, with the selection and interaction effects being the same as the single currency case.

\[
  \begin{aligned}
    A_i & = (w_{pi} - w_{bi}) \times (R_{bi} - R_{ci} - R_l) \\
    S_i & = w_{bi} \times (R_{pi} - R_{bi}) \\
    I_i & = (w_{pi} - w_{bi}) \times (R_{pi} - R_{bi})
  \end{aligned}
\]

where $R_l$ is given by

\[
R_l = \sum^n_{i=1}\left(w_{bi} \times (R_{bi} - R_{ci}) \right)
\]

The contribution from currency effects are analagous to asset allocation. The first, _currency management_ effect is the contribution due to the underlying assets and currency forwards (if present) and is defined as

\[
C_i = (w_{pi} - w_{bi}) \times (R_{cei} - R_{ce}) + (w_{pfi} - w_{bfi}) \times (R_{fi} - R_{ce}) \\
\]

where $R_{ce}$ is given by

\[
R_{ce} = \sum^n_{i=1}\left(w_{bi} \times R_{cei} \right)
\]

The second, _forward premium_ effect is given by

\[
C_i = (w_{pi} - w_{bi}) \times (R_{fpi} - R_{fp}) \\
\]

where $R_{fp}$ is given by

\[
R_{fp} = \sum^n_{i=1}\left(w_{bi} \times R_{fpi} \right)
\]

#### Multi-currency geometric attribution

For multi-currency geometric attribution the approach adopted is that outlined in _Practical Portfolio Performance Measurement and Attribution by Bacon [-@bacon2008practical]_.

As before, the total portfolio and benchmark returns in the base currency are given by

\[
R_p = \sum^n_{i=1}\left(w_{pi} \times R_{pi} \right) \\
R_b = \sum^n_{i=1}\left(w_{bi} \times R_{bi} \right)
\]

Let's define the portfolio and benchmark returns in _local_ currency in category $i$ as $R_{pLi}$ and $R_{bLi} respectively. The total portfolio and benchmark returns in local currency are then given by

\[
R_{pL} = \sum^n_{i=1}\left(w_{pi} \times R_{pLi} \right) \\
R_{bL} = \sum^n_{i=1}\left(w_{bi} \times R_{bLi} \right)
\]

The allocation semi-notional return in the local currency is given by

\[
R_{bSL} = \sum^n_{i=1}\left(w_{pi} \times R_{bLi} \right)
\]

The deviation from the index weighting hedged into the base currency is given by

\[
R_{bSH} = \sum^n_{i=1}(((w_{pi} - w_{bi}) \times R_{bHi}) + w_{bi} \times R_{bLi})
\]

where $R_{bHi}$, known as the _hedged index return_ is as defined below, with $R_{fi}$ as defined earlier

\[
R_{bHi} = \frac{(1 + R_{bi})}{(1 + R_{fi})} - 1
\]

The allocation and selection effects for category $i$ are defined as

\[
A_i = (w_{pi} - w_{bi}) \times \left(\frac{(1 + R_{bHi})}{(1 + R_{bL})} - 1 \right) \\
S_i = w_{pi} \times \left(\frac{(1 + R_{pLi})}{(1 + R_{bLi})} - 1 \right) \times \left(\frac{(1 + R_{bLi})}{(1 + R_{bSL})} \right)
\]

and the total allocation and selection effect across all categories is given by

\[
A = \frac{(1 + R_{bsH})}{(1 + R_{bL})} - 1 \\
S = \frac{(1 + R_{pL})}{(1 + R_{bSL})} - 1
\]

The currency effects can be broken into two components, one, what Carl Bacon calls _naive currency attribution_ and the other _costs of hedging_. 

The naive currency effect is the difference between the base currency return of the portfolio and the weighted average local return and is defined give by the expression below. It is termed naive because it does not make allowance for the transfer of the costs of hedging due to the allocation bets taken by the portfolio manager and because it does not reflect the compounding effects between market or currency returns.

\[
C = \frac{(1 + R_p)}{(1 + R_{pL})} \times \frac{(1 + R_{bL})}{(1 + R_b)} - 1
\]

The costs of hedging represents the costs or benefit of hedging the asset allocator's decision back to the neutral currency benchmark and is given by

\[
H =  \frac{(1 + R_{bsL})}{(1 + R_{bSH})} - 1
\]

All of these effects now compound to the total geometric express return as show in the decomposition below

\[
E^G = \frac{(1 + R_p)}{(1 + R_b)} - 1 = (1 + A) \times (1 + S) \times (1 + C) \times (1 + H) - 1 \\
E^G = \left(\frac{(1 + R_{bsH})}{(1 + R_{bL})} \right) \times \left(\frac{(1 + R_{pL})}{(1 + R_{bSL})} \right) \times \left(\frac{(1 + R_p)}{(1 + R_{pL})} \times \frac{(1 + R_{bL})}{(1 + R_b)} \right) \times \left(\frac{(1 + R_{bsL})}{(1 + R_{bSH})} \right) - 1
\]


### <ins>Package basics</ins>

The `PortfolioAttribution` package supports multiple methodologies and allows for multi-period attribution analysis. It also support multi-currency portfolios in which case it reports the currency effects. The package also supports the ability to define custom hierarchies to perform multi-level attribution. The various other companion vignettes in this package contain illustrative examples. They use sample data sets that are included with the package so that the users can try these examples on their own.

The attribution functions in this package employ an interface in terms of weights & returns. In other words, it is expected that any positions, prices, transactions and other complexities that go into computing the desired weight and return to use in attribution analysis, has occurred in advance and the resulting data is feed in as input to these functions.

The main functions of interest are `Attribution`, `Attribution.levels` and `AttributionFixedIncome`. You can use the `help` command or the `?` shortcut on any of these functions to peruse their documentation.

Some common aspects to the different functions are:

* the returns and weights have to be specified as decimal numbers and not percentages
* the returns have to be in the form of a $T \times n$ `xts`, `data.frame` or `matrix` of returns
* the weights have to be in the form of a vector or $T \times n$ `xts`, `data.frame` or `matrix` of returns. When the weights are in the form a vector it is assumed that the weights are reset to the target prior to each period
* the rows in the returns & weights data represent periods while the columns represent assets or categories
* the package requires that the return data have row indexes defined as dates or periods compatible with the `xts` package
* the portfolio & benchmark returns & weights must have the same number of assets or categories for each date. If a portfolio or benchmark does not hold an asset or category that is in the other, a return and weight of 0 must be specified. In other words the dimensions of the portfolio & benchmark data must match.
* similarly, in a multi-period data set, if an asset or category drops out of the portfolio or benchmark, a return and weight of 0 must be specified. In other words the number of assets or categories for each period must be the same.
* the package treats the weights provided as __end-of-peroid__ weights. They can be thought of as taking effect immediately after the close of the bar. So, a weight specified for March 31 will actually be in effect starting April 1 through the next period. This convention was chosen because it fits with common usage, and because it simplifies date sub-setting via endpoints.
* in addition to the attribution effects, the attribution methods also report the total excess returns for each period and annualizes when appropriate
* in the case of multi-currency arithmetic attribution, the weights & returns of forward contracts in the portfolio & benchmarks can also be provided
* the type of object returned is a `list`

There are a number of unit tests included as part of the package that can be executed & examined to better understand the different functions and their expected behavior. These unit tests are available in the `tests` folder and employ the framework defined in the `testthat` package.

### <ins>References</ins>
