---
title: "Introduction to multi-currency Portfolio Attribution"
author: "[Anand Krishnakumar](https://github.com/anandkkumar)"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
bibliography: introduction.bib
vignette: >
  %\VignetteIndexEntry{Introduction to multi-currency Portfolio Attribution}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

### <ins>Multi-currency arithmetic attribution</ins>

With arithmetic attribution, the methodology employed follows that described by _Ankrim and Hensel [-@ankrim1994multicurrency]_. According to that approach, the currency return is comprised of two components: the unpredictable _currency surprise_ and the predictable interest rate differential or _forward premium_ between the appropriate currencies.

The currency surprise and forward premium in currency $i$ are given by

\[
  \begin{aligned}
    R_{ei} & = \frac{S_i^{t+1} - F_i^{t+1}}{S_i^t} \\
    R_{di} & = \frac{F_i^{t+1}}{S_i^t} - 1
  \end{aligned}
\]

where $S_i^t$ and $S_t^{t+1}$ are the spot rates of the currency $i$ at times $t$ and $t+1$ and $F_i^{t+1}$ is the forward exchange rate of the currency $i$ at time $t$ for conversion through a forward contract at time $t+1$.

Then currency return is the sum of the currency surprise and the forward premium

\[
R_{ci} = R_{ei} + R_{di}
\]

Assuming the currency surprise and forward premiums are the same in the portfolio & benchmark, the total returns to the portfolio and benchmark can be expanded to include these currency returns

\[
  \begin{aligned}
    R_p & = \sum^n_{i=1}\left(w_{pi} \times(R_{pi} - R_{ei} - R_{di})\right) + \sum^n_{i=1}\left(w_{pi} \times R_{ei}\right) + \sum^n_{i=1}\left(w_{pi} \times R_{di}\right) \\
    R_b & = \sum^n_{i=1}\left(w_{bi} \times(R_{bi} - R_{ei} - R_{di})\right) + \sum^n_{i=1}\left(w_{bi} \times R_{ei}\right) + \sum^n_{i=1}\left(w_{bi} \times R_{di}\right)
  \end{aligned}
\]

If the portfolio and benchmark also includes forward currency contracts, these can then be further isolated from the rest of the sources of return. If the weights of the forward contracts in the portfolio and benchmark are $w_{pfi}$ and $w_{bfi}$ respectively, then the forward return due to the currency contracts can be expressed as

\[
  R_{fi} = \frac{S_i^{t+1}}{F_i^{t+1}} - 1
\]

Note that the forward return is linked to the currency surprise and forward premium by the formula

\[
  R_{fi} = \frac{R_{ei}}{(1 + R_{di})}
\]


Assuming the currency forward contract returns are the same in the portfolio & benchmark, the total returns to the portfolio and benchmark with the forward contracts included are now expressed as

\[
  \begin{aligned}
    R_p & = \sum^n_{i=1}\left(w_{pi} \times(R_{pi} - R_{ei} - R_{di})\right) + \sum^n_{i=1}\left(w_{pi} \times R_{ei}\right) + \sum^n_{i=1}\left(w_{pi} \times R_{di}\right) + \sum^n_{i=1}\left(w_{pfi} \times R_{fi}\right) \\
    R_b & = \sum^n_{i=1}\left(w_{bi} \times(R_{bi} - R_{ei} - R_{di})\right) + \sum^n_{i=1}\left(w_{bi} \times R_{ei}\right) + \sum^n_{i=1}\left(w_{bi} \times R_{di}\right) + \sum^n_{i=1}\left(w_{bfi} \times R_{fi}\right)
  \end{aligned}
\]

The allocation, selection and interaction effects for category $i$ are as shown below, with the selection and interaction effects being the same as the single currency case.

\[
  \begin{aligned}
    A_i & = (w_{pi} - w_{bi}) \times (R_{bi} - R_{ci} - R_l) \\
    S_i & = w_{bi} \times (R_{pi} - R_{bi}) \\
    I_i & = (w_{pi} - w_{bi}) \times (R_{pi} - R_{bi})
  \end{aligned}
\]

where $R_l$ is given by

\[
R_l = \sum^n_{i=1}\left(w_{bi} \times (R_{bi} - R_{ci}) \right)
\]

The contribution from currency effects are analogous to asset allocation. The first, _currency management_ effect is the contribution due to the underlying assets and currency forwards (if present) and is defined as

\[
C_i = (w_{pi} - w_{bi}) \times (R_{ei} - R_e) + (w_{pfi} - w_{bfi}) \times (R_{fi} - R_e) \\
\]

where $R_e$ is given by

\[
R_e = \sum^n_{i=1}\left(w_{bi} \times R_{ei} \right)
\]

The second, _forward premium_ effect is given by

\[
C_i = (w_{pi} - w_{bi}) \times (R_{di} - R_d) \\
\]

where $R_d$ is given by

\[
R_d = \sum^n_{i=1}\left(w_{bi} \times R_{di} \right)
\]

### <ins>Multi-currency geometric attribution</ins>

For multi-currency geometric attribution the approach adopted is that outlined in _Practical Portfolio Performance Measurement and Attribution by Bacon [-@bacon2008practical]_.

As before, the total portfolio and benchmark returns in the base currency are given by

\[
R_p = \sum^n_{i=1}\left(w_{pi} \times R_{pi} \right) \\
R_b = \sum^n_{i=1}\left(w_{bi} \times R_{bi} \right)
\]

Let's define the portfolio and benchmark returns in _local_ currency in category $i$ as $R_{pli}$ and $R_{bli}$ respectively. The total portfolio and benchmark returns in local currency are then given by

\[
R_{pl} = \sum^n_{i=1}\left(w_{pi} \times R_{pli} \right) \\
R_{bl} = \sum^n_{i=1}\left(w_{bi} \times R_{bli} \right)
\]

The allocation semi-notional return in the local currency is given by

\[
R_{bsl} = \sum^n_{i=1}\left(w_{pi} \times R_{bli} \right)
\]

The deviation from the index weighting hedged into the base currency is given by

\[
R_{bsh} = \sum^n_{i=1}(((w_{pi} - w_{bi}) \times R_{bhi}) + w_{bi} \times R_{bli})
\]

with $R_{bhi}$, known as the _hedged index return_ is as defined below

\[
R_{bhi} = \frac{(1 + R_{bi})}{(1 + R_{bfi})} - 1
\]

where $R_{bfi}$ is the forward return in currency $i$ on currency contracts in the benchmark

\[
  R_{bfi} = \frac{S_i^{t+1}}{F_i^{t+1}} - 1
\]

Note that the hedged index return is also related to the local benchmark return and forward premium through the relationship below

\[
R_{bhi} = \left((1 + R_{bli}) \times (1 + R_{di}) \right) - 1
\]

The allocation and selection effects for category $i$ are defined as

\[
A_i = (w_{pi} - w_{bi}) \times \left(\frac{(1 + R_{bhi})}{(1 + R_{bl})} - 1 \right) \\
S_i = w_{pi} \times \left(\frac{(1 + R_{pli})}{(1 + R_{bli})} - 1 \right) \times \left(\frac{(1 + R_{bli})}{(1 + R_{bsl})} \right)
\]

and the total allocation and selection effect across all categories is given by

\[
A = \frac{(1 + R_{bsh})}{(1 + R_{bl})} - 1 \\
S = \frac{(1 + R_{pl})}{(1 + R_{bsl})} - 1
\]

The currency effects can be broken into two components, one, what Carl Bacon calls _naive currency attribution_ and the other _costs of hedging_. 

The naive currency effect is the difference between the base currency return of the portfolio and the weighted average local return and is defined give by the expression below. It is termed naive because it does not make allowance for the transfer of the costs of hedging due to the allocation bets taken by the portfolio manager and because it does not reflect the compounding effects between market or currency returns.

\[
C = \frac{(1 + R_p)}{(1 + R_{pl})} \times \frac{(1 + R_{bl})}{(1 + R_b)} - 1
\]

The costs of hedging represents the costs or benefit of hedging the asset allocator's decision back to the neutral currency benchmark and is given by

\[
H =  \frac{(1 + R_{bsl})}{(1 + R_{bsh})} - 1
\]

All of these effects now compound to the total geometric express return as show in the decomposition below

\[
  \begin{aligned}
    E^G & = \frac{(1 + R_p)}{(1 + R_b)} - 1 = (1 + A) \times (1 + S) \times (1 + C) \times (1 + H) - 1 \\
    E^G & = \left(\frac{(1 + R_{bsh})}{(1 + R_{bl})} \right) \times \left(\frac{(1 + R_{pl})}{(1 + R_{bsl})} \right) \times \left(\frac{(1 + R_p)}{(1 + R_{pl})} \times \frac{(1 + R_{bl})}{(1 + R_b)} \right) \times \left(\frac{(1 + R_{bsl})}{(1 + R_{bsh})} \right) - 1
    \end{aligned}
\]

The `PortfolioAttribution` package also supports any forward contracts that may be held in the portfolio or benchmark, as in the arithmetic case. The total portfolio & benchmark returns then become
\[
  \begin{aligned}
    R_p & = \sum^n_{i=1}\left(w_{pi} \times R_{pi} \right) + \sum^n_{i=1}\left(w_{pfi} \times R_{pfi}\right) \\
    R_b & = \sum^n_{i=1}\left(w_{bi} \times R_{bi} \right) + \sum^n_{i=1}\left(w_{bfi} \times R_{bfi}\right)
  \end{aligned}
\]

where $R_{pfi}$ and $R_{bfi}$ are the forward returns in currency $i$ on currency contracts in the portfolio and benchmark respectively.

### <ins>References</ins>
