---
title: "Introduction to Opturo's Portfolio Attribution"
author: "[Anand Krishnakumar](https://github.com/anandkkumar)"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
bibliography: introduction.bib
vignette: >
  %\VignetteIndexEntry{Introduction to Opturo's Portfolio Attribution}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## <ins>Preliminaries</ins>

The purpose of this vignette is to describe, at a high-level, the **proprietary** methodologies implemented by *Opturo's Investment Analytics* attribution engine in order to illustrate the differences between them and the standard attribution techniques as documented in _Practical Portfolio Performance Measurement and Attribution by Bacon [-@bacon2008practical]_. For a brief introduction to portfolio performance attribution, please refer to the [introduction vignette](introduction.html).

The Opturo engine supports both _Brinson, Hood, Beebower. [-@brinson1986determinants]_ and _Brinson and Fachler [-@brinson1985measuring]_ methodologies and has support for arithmetic and geometric excess return attribution. In addition, it supports reporting the _Interaction effect_ separately, combined with the _Selection effect_ (termed as _Selection Plus_ by Opturo) or combined with the _Allocation effect_ (termed as _Allocation Plus_ by Opturo). The engine also supports currency attribution.

For the purposes of this comparison, we will focus on the _Brinson and Fachler_ arithmetic attribution techniques with the _Interaction effect_ combined into either the _Selection effect_ or the _Allocation effect_

## <ins>Opturo Attribution effects</ins>

### Data inputs

The Opturo attribution methodologies require the following inputs for each asset $i$:

* beginning of period benchmark weights $w_{bi}$

* benchmark returns $R_{bi}$

* beginning of period portfolio weights $w_{pi}$

* average portfolio weights $w\_avg_{pi}$

* holdings-based portfolio returns $R\_h_{pi}$

* transactions-based actual portfolio returns $R\_trans_{pi}$

The segment level weights and returns $w_{bs}$, $R_{bs}$, etc. can be aggregated up from the security level data.

The arithmetic excess return for the portfolio over the benchmark is computed using the average weights and transactions-based returns of the assets in the portfolio.


\[
E^A = R_p - R_b = \sum ^n_{i=1} (w\_avg_{pi} \times R\_trans_{pi}) - \sum ^n_{i=1} (w_{bi} \times R_{bi})
\]

where $Rp$ and $Rb$ is total portfolio & benchmark returns for that period.

### Data substitutions

In addition to portfolios being more concentrated then a benchmark, it is also possible for a benchmark to not hold a particular security that is in the portfolio. In these cases, in addition to the weights for those assets being appropriately set to zero, for the attribution effects to be computed accurately, it's appropriate to impute the returns as well. When the weight of an asset $i$ in a portfolio is zero, it's holding-based $R\_h_{pi}$ and transactions-based returns $R\_trans_{pi}$ are both set to that of benchmark asset, $R_{bi}$. Similarly, if the weight an asset $i$ in the benchmark is zero, it's return $R_{bi}$ is set to the holding-based return of the corresponding asset in the portfolio, $R\_h_{pi}$. For the rest of this vignette, it's assumed these substitutions have been made.


###  Selection Plus

With Opturo's _Selection Plus_ method, the allocation and selection effects at the segment level are as defined below. In this method, the Interaction effect is combined into the Selection effects.

\[
  \begin{aligned}
    A_s &= (w_{ps} - w_{bs})\times (R_{bs} - R_b) \\
    S_s &= w_{ps}\times(R\_h_{ps} - R_{bs}) \\
  \end{aligned}
\]

The allocation and selection effects at the security level are as defined below

\[
  \begin{aligned}
    A_i &= 0 \\
    S_i &= (w_{pi} - w_{bi})\times (R_{bi} - R_b) \\
  \end{aligned}
\]


### Allocation Plus

With Opturo's _Allocation Plus_ method, the allocation and selection effects at the segment level are as defined below. In this method, the Interaction effect is combined into the Allocation effects.

\[
  \begin{aligned}
    A_s &= (w_{ps} - w_{bs})\times (R\_h_{ps} - R_b) \\
    S_s &= w_{bs}\times(R\_h_{ps}-R_{bs}) \\
  \end{aligned}
\]

The allocation and selection effects at the security level are as defined below

\[
  \begin{aligned}
    A_i &= 0 \\
    S_i &= (w_{pi} - w_{bi})\times (R\_h_{pi} - R_b) \\
  \end{aligned}
\]

### Invest Effect

The _Invest effect_ is a *proprietary* effect defined by Opturo which is meant to capture excess portfolio returns that are attributable to compounding effects rather than an active decision. At the segment-level it is the sum of the invest effects for all securities in that segment. The invest effect at the security level defined as follows:

\[
  \begin{aligned}
    Inv_i &= w_{bi}\times(R\_h_{pi}-R_{bi}) \\
    Inv_s &= \sum ^n_{i=1} Inv_i \\
  \end{aligned}
\]

### Trade Effect

The _Trade effect_ is another *proprietary* effect defined by Opturo which is meant to capture the effect of trading and is the difference between if one were to just buy and hold the securities rather than considering trades throughout the day. The trade effect at the segment and security levels are defined as:

\[
  \begin{aligned}
    Trade_s &= (w\_avg_{ps} \times R\_trans_{ps}) - (w_{ps} \times R\_h_{ps}) \\
    Trade_i &= (w\_avg_{pi} \times R\_trans_{pi}) - (w_{pi} \times R\_h_{pi}) \\
  \end{aligned}
\]



## <ins>Multi-currency portfolios</ins>

The Opturo attribution engine also computes a _currency effect_ in the case of multi-currency portfolios. The data inputs needs in this case are as follows:

* beginning of period benchmark weights $w_{bi}$

* benchmark returns in the local currency $R\_local_{bi}$

* benchmark returns in the base currency $R\_base_{bi}$

* beginning of period portfolio weights $w_{pi}$

* average portfolio weights $w\_avg_{pi}$

* holdings-based portfolio returns in local currency $R\_h\_local_{pi}$

* holdings-based portfolio returns in base currency $R\_h\_base_{pi}$

* transactions-based actual portfolio returns $R\_trans\_local_{pi}$

* transactions-based actual portfolio returns $R\_trans\_base_{pi}$

At the segment-level the currency effect is the sum of the currency effects for all securities in that segment. The currency effect at the security level defined as follows:

\[
  \begin{aligned}
    Curr_i & = 
    \begin{cases}
      (w_{pi} - w_{bi})\times (R\_base_{bi} - R\_local_{bi}) & \small \text{ if } w_{bi} \neq 0 \\
      (w\_avg_{pi} - w_{bi})\times (R\_trans\_base_{pi} - R\_trans\_local_{pi}) & \small \text{ if } w_{bi} = 0 \\
    \end{cases} \\
    Curr_s & = \sum ^n_{i=1} Curr_i \\
  \end{aligned}
\]

The allocation, selection, invest and trade effects are as defined earlier and are computed using the local currency returns. The following sections summarize all the effects in both approaches. 

### Selection Plus

\[
  \begin{aligned}
    A_s &= (w_{ps} - w_{bs})\times (R\_local_{bs} - R\_local_b) \\
    A_i &= 0 \\
    S_s &= w_{ps}\times(R\_h\_local_{ps}-R\_local_{bs}) \\
    S_i &= (w_{pi} - w_{bi})\times (R\_local_{bi} - R\_local_b) \\
    Inv_i &= w_{bi}\times(R\_h\_local_{pi}-R\_local_{bi}) \\
    Inv_s &= \sum ^n_{i=1} Inv_i \\
    Trade_s &= (w\_avg_{ps} \times R\_trans\_local_{ps}) - (w_{ps} \times R\_h\_local_{ps}) \\
    Trade_i &= (w\_avg_{pi} \times R\_trans\_local_{pi}) - (w_{pi} \times R\_h\_local_{pi}) \\
    Curr_i & = 
    \begin{cases}
      (w_{pi} - w_{bi})\times (R\_base_{bi} - R\_local_{bi}) & \small \text{ if } w_{bi} \neq 0 \\
      (w\_avg_{pi} - w_{bi})\times (R\_trans\_base_{pi} - R\_trans\_local_{pi}) & \small \text{ if } w_{bi} = 0 \\
    \end{cases} \\
    Curr_s & = \sum ^n_{i=1} Curr_i \\
  \end{aligned}
\]


### Allocation Plus

\[
  \begin{aligned}
    A_s &= (w_{ps} - w_{bs})\times (R\_h\_local_{ps} - R\_local_b) \\
    A_i &= 0 \\
    S_s &= w_{bs}\times(R\_h\_local_{ps}-R\_local_{bs}) \\
    S_i &= (w_{pi} - w_{bi})\times (R\_h\_local_{pi} - R\_local_b) \\
    Inv_i &= w_{bi}\times(R\_h\_local_{pi}-R\_local_{bi}) \\
    Inv_s &= \sum ^n_{i=1} Inv_i \\
    Trade_s &= (w\_avg_{ps} \times R\_trans\_local_{ps}) - (w_{ps} \times R\_h\_local_{ps}) \\
    Trade_i &= (w\_avg_{pi} \times R\_trans\_local_{pi}) - (w_{pi} \times R\_h\_local_{pi}) \\
    Curr_i & = 
    \begin{cases}
      (w_{pi} - w_{bi})\times (R\_base_{bi} - R\_local_{bi}) & \small \text{ if } w_{bi} \neq 0 \\
      (w\_avg_{pi} - w_{bi})\times (R\_trans\_base_{pi} - R\_trans\_local_{pi}) & \small \text{ if } w_{bi} = 0 \\
    \end{cases} \\
    Curr_s & = \sum ^n_{i=1} Curr_i \\
  \end{aligned}
\]


## <ins>Multi-period analysis</ins>

With multi-period arithmetic attribution there is a need to smooth periodic attribution effects by employing some sort of linking algorithm. The proprietary approach adopted by Opturo is a variation of what is commonly known as a 'backward-looking' compounding algorithm. Given an asset's raw allocation or selection effect $A_i$, $S_i$ and total portfolio return $R_p$ in periods $t-1$ and $t$, the corresponding adjusted effect in period $t$ is given by:

\[
  \begin{aligned}
    A\_adj_i^t &= A_i^{t-1} + A_i^t \times (1 + R_p^{t-1}) \\
    S\_adj_i^t &= S_i^{t-1} + S_i^t \times (1 + R_p^{t-1})
  \end{aligned}
\]

For invest effects given an asset's raw invest effects $Inv_i$ in period $t-1$, the corresponding adjusted effect in period $t$ is given by:

\[
  \begin{aligned}
    Inv\_adj_i^t &= Inv_i^{t-1} + (w_{bi}^t \times R\_h_{pi}^t) \times (1 + R_p^{t-1}) - (w_{bi}^t \times R_{bi}^t) \times (1 + R_b^{t-1}) \\
    Inv\_adj_s &= \sum ^n_{i=1} Inv_i \\
  \end{aligned}
\]


## <ins>Comparison of Opturo's methods to standard methods</ins>


* The _top-down_ method implemented in the package is equivalent to Opturo's _Selection Plus_ approach with the allocation & selection effects as defined earlier. The package has no special treatment for security-level effects.
* The _bottom-up_ method implemented in the package is equivalent to Opturo's _Allocation Plus_ approach with the allocation & selection effects as defined earlier. The package has no special treatment for security-level effects.
* The _Trade_ and _Invest_ effects, being proprietary, have no equivalent in the standard methods implemented in the _PortfolioAttribution_ package. For the purposes of comparison, it would be most appropriate to combine the _Trade_ and _Invest_ effects into the _Selection_ effects prior to comparison with standard methods.
* The currency effect in the package is equivalent to the difference between running the attribution with local currency and base currency and the net values are consistent with Opturo.
* The multi-period linking algorithms employed by Opturo has no exact equivalent. The package implements a similar standard smoothing method as described by _GRAP [-@grap1997]_ which is implemented by the package. With the _GRAP_ smoothing algorithm, given an asset's raw allocation or selection effect $A_i$, $S_i$ and asset's portfolio return $R_{pi}$ and benchmark return $R_{bi}$ in period $t$ ranging from 1 to $T$, the corresponding adjusted effect in period $t$ is given by:

\[
  \begin{aligned}
    A\_adj_i^t & = 
    \begin{cases}
      A_i^{1} \times ∏^{T}_{j=2} (1+R_{bi}^j) & \small \text{ if }  t = 1 \\
      A_i^{t} \times (∏^{t-1}_{j=1} (1+R_{pi}^j) \times ∏^{T}_{j=t+1} (1+R_{bi}^j)) & \small \text{ if } 2 < t < T \\
      A_i^{T} \times (∏^{T-1}_{j=1} (1+R_{pi}^j)) & \small \text{ if } t = T \\
    \end{cases} \\
    \\
    S\_adj_i^t & = 
    \begin{cases}
      S_i^{1} \times ∏^{T}_{j=2} (1+R_{bi}^j) & \small \text{ if }  t = 1 \\
      S_i^{t} \times (∏^{t-1}_{j=1} (1+R_{pi}^j) \times ∏^{T}_{j=t+1} (1+R_{bi}^j)) & \small \text{ if } 2 < t < T \\
      S_i^{T} \times (∏^{T-1}_{j=1} (1+R_{pi}^j)) & \small \text{ if } t = T \\
    \end{cases}
  \end{aligned}
\]

## <ins>References</ins>
